[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx prisma generate"

[deploy]
startCommand = "cd backend && node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
